[2025-05-27T19:55:05.371+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.generate_inventory_returns manual__2025-05-27T19:49:56+00:00 [queued]>
[2025-05-27T19:55:05.376+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.generate_inventory_returns manual__2025-05-27T19:49:56+00:00 [queued]>
[2025-05-27T19:55:05.377+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-05-27T19:55:05.382+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_inventory_returns> on 2025-05-27 19:49:56+00:00
[2025-05-27T19:55:05.386+0000] {standard_task_runner.py:57} INFO - Started process 126 to run task
[2025-05-27T19:55:05.388+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'generate_inventory_returns', 'manual__2025-05-27T19:49:56+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmpy3d3ysvk']
[2025-05-27T19:55:05.391+0000] {standard_task_runner.py:85} INFO - Job 335: Subtask generate_inventory_returns
[2025-05-27T19:55:05.415+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.generate_inventory_returns manual__2025-05-27T19:49:56+00:00 [running]> on host a552bff97440
[2025-05-27T19:55:05.656+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='generate_inventory_returns' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T19:49:56+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T19:49:56+00:00'
[2025-05-27T19:55:05.657+0000] {logging_mixin.py:154} INFO - Starting inventory and returns data generation...
[2025-05-27T19:55:05.657+0000] {logging_mixin.py:154} INFO - Retrieving existing data for inventory and returns generation...
[2025-05-27T19:55:05.677+0000] {logging_mixin.py:154} INFO - Generating inventory data...
[2025-05-27T19:55:05.681+0000] {logging_mixin.py:154} INFO - Found 500 existing inventory records, skipping generation
[2025-05-27T19:55:05.684+0000] {logging_mixin.py:154} INFO - Generating returns data...
[2025-05-27T19:55:05.701+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "original_sale_date" of relation "ods_returns" does not exist
LINE 1: ...ity_returned, return_condition, original_sale_id, original_s...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/walmart_etl_dag.py", line 105, in etl_generate_inventory_returns
    result = generate_inventory_returns_data()
  File "/opt/airflow/walmart-etl/generate_inventory_returns_data.py", line 244, in main
    returns_data = generate_returns_data(existing_data, num_records=200)
  File "/opt/airflow/walmart-etl/generate_inventory_returns_data.py", line 228, in generate_returns_data
    df_returns.to_sql('ods_returns', engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1920, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1470, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1461, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1023, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 929, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "original_sale_date" of relation "ods_returns" does not exist
LINE 1: ...ity_returned, return_condition, original_sale_id, original_s...
                                                             ^

[SQL: INSERT INTO ods_returns (return_id, return_date, product_id, store_id, reason_code, return_amount, quantity_returned, return_condition, original_sale_id, original_sale_date, source_system, load_timestamp) VALUES (%(return_id)s, %(return_date)s, %(product_id)s, %(store_id)s, %(reason_code)s, %(return_amount)s, %(quantity_returned)s, %(return_condition)s, %(original_sale_id)s, %(original_sale_date)s, %(source_system)s, %(load_timestamp)s)]
[parameters: ({'return_id': 'RET000001', 'return_date': datetime.date(2025, 5, 18), 'product_id': 'ab7a3874-c28a-4db5-9', 'store_id': 'Norfolk_Nebraska_68701', 'reason_code': 'SIZE', 'return_amount': Decimal('19.05'), 'quantity_returned': 3, 'return_condition': 'Like New', 'original_sale_id': 'SALE59917', 'original_sale_date': datetime.date(2025, 4, 23), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688401)}, {'return_id': 'RET000002', 'return_date': datetime.date(2025, 5, 19), 'product_id': '711fcb70-5642-4984-a', 'store_id': 'Belmont_MA_2478', 'reason_code': 'COLOR', 'return_amount': Decimal('11.25'), 'quantity_returned': 3, 'return_condition': 'New', 'original_sale_id': 'SALE81277', 'original_sale_date': datetime.date(2025, 5, 1), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688409)}, {'return_id': 'RET000003', 'return_date': datetime.date(2025, 4, 29), 'product_id': '484acbc4-e41f-4b8b-a', 'store_id': 'Flower Mound_Texas_75028', 'reason_code': 'PERF', 'return_amount': Decimal('68.96'), 'quantity_returned': 4, 'return_condition': 'Used', 'original_sale_id': 'SALE20578', 'original_sale_date': datetime.date(2025, 4, 19), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688416)}, {'return_id': 'RET000004', 'return_date': datetime.date(2025, 5, 10), 'product_id': '69f9cc9b-66e8-4c45-8', 'store_id': 'Oro Valley_Arizona_85737', 'reason_code': 'LATE', 'return_amount': Decimal('17.94'), 'quantity_returned': 3, 'return_condition': 'Damaged', 'original_sale_id': 'SALE38464', 'original_sale_date': datetime.date(2025, 4, 28), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688428)}, {'return_id': 'RET000005', 'return_date': datetime.date(2025, 5, 25), 'product_id': 'a2f02b89-823f-44c6-9', 'store_id': 'Lorain_Ohio_44052', 'reason_code': 'PERF', 'return_amount': Decimal('19.42'), 'quantity_returned': 2, 'return_condition': 'Like New', 'original_sale_id': 'SALE82501', 'original_sale_date': datetime.date(2025, 5, 21), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688435)}, {'return_id': 'RET000006', 'return_date': datetime.date(2025, 4, 28), 'product_id': '376a9935-783f-428b-8', 'store_id': 'Collierville_Tennessee_38017', 'reason_code': 'PERF', 'return_amount': Decimal('79.96'), 'quantity_returned': 2, 'return_condition': 'New', 'original_sale_id': 'SALE24305', 'original_sale_date': datetime.date(2025, 4, 17), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688441)}, {'return_id': 'RET000007', 'return_date': datetime.date(2025, 5, 1), 'product_id': '621306c7-2eb8-4951-9', 'store_id': 'Durango_Colorado_81301', 'reason_code': 'LATE', 'return_amount': Decimal('87.14'), 'quantity_returned': 2, 'return_condition': 'Defective', 'original_sale_id': 'SALE29979', 'original_sale_date': datetime.date(2025, 4, 10), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688447)}, {'return_id': 'RET000008', 'return_date': datetime.date(2025, 4, 30), 'product_id': '420a1e94-4967-4387-8', 'store_id': 'Galesburg_Illinois_61401', 'reason_code': 'CHANGE', 'return_amount': Decimal('5.78'), 'quantity_returned': 1, 'return_condition': 'Used', 'original_sale_id': 'SALE60337', 'original_sale_date': datetime.date(2025, 3, 31), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688470)}  ... displaying 10 of 200 total bound parameter sets ...  {'return_id': 'RET000199', 'return_date': datetime.date(2025, 5, 16), 'product_id': '5564d9af-7a2e-4f8b-9', 'store_id': 'Germantown_Tennessee_38138', 'reason_code': 'CHANGE', 'return_amount': Decimal('19.90'), 'quantity_returned': 1, 'return_condition': 'Like New', 'original_sale_id': 'SALE83255', 'original_sale_date': datetime.date(2025, 4, 26), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 689611)}, {'return_id': 'RET000200', 'return_date': datetime.date(2025, 5, 1), 'product_id': '488a83b1-98f1-4345-a', 'store_id': 'Hastings_Nebraska_68901', 'reason_code': 'WRONG', 'return_amount': Decimal('39.20'), 'quantity_returned': 5, 'return_condition': 'Like New', 'original_sale_id': 'SALE72615', 'original_sale_date': datetime.date(2025, 4, 3), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 689616)})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-05-27T19:55:05.720+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=walmart_etl_dag, task_id=generate_inventory_returns, execution_date=20250527T194956, start_date=20250527T195505, end_date=20250527T195505
[2025-05-27T19:55:05.728+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 335 for task generate_inventory_returns ((psycopg2.errors.UndefinedColumn) column "original_sale_date" of relation "ods_returns" does not exist
LINE 1: ...ity_returned, return_condition, original_sale_id, original_s...
                                                             ^

[SQL: INSERT INTO ods_returns (return_id, return_date, product_id, store_id, reason_code, return_amount, quantity_returned, return_condition, original_sale_id, original_sale_date, source_system, load_timestamp) VALUES (%(return_id)s, %(return_date)s, %(product_id)s, %(store_id)s, %(reason_code)s, %(return_amount)s, %(quantity_returned)s, %(return_condition)s, %(original_sale_id)s, %(original_sale_date)s, %(source_system)s, %(load_timestamp)s)]
[parameters: ({'return_id': 'RET000001', 'return_date': datetime.date(2025, 5, 18), 'product_id': 'ab7a3874-c28a-4db5-9', 'store_id': 'Norfolk_Nebraska_68701', 'reason_code': 'SIZE', 'return_amount': Decimal('19.05'), 'quantity_returned': 3, 'return_condition': 'Like New', 'original_sale_id': 'SALE59917', 'original_sale_date': datetime.date(2025, 4, 23), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688401)}, {'return_id': 'RET000002', 'return_date': datetime.date(2025, 5, 19), 'product_id': '711fcb70-5642-4984-a', 'store_id': 'Belmont_MA_2478', 'reason_code': 'COLOR', 'return_amount': Decimal('11.25'), 'quantity_returned': 3, 'return_condition': 'New', 'original_sale_id': 'SALE81277', 'original_sale_date': datetime.date(2025, 5, 1), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688409)}, {'return_id': 'RET000003', 'return_date': datetime.date(2025, 4, 29), 'product_id': '484acbc4-e41f-4b8b-a', 'store_id': 'Flower Mound_Texas_75028', 'reason_code': 'PERF', 'return_amount': Decimal('68.96'), 'quantity_returned': 4, 'return_condition': 'Used', 'original_sale_id': 'SALE20578', 'original_sale_date': datetime.date(2025, 4, 19), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688416)}, {'return_id': 'RET000004', 'return_date': datetime.date(2025, 5, 10), 'product_id': '69f9cc9b-66e8-4c45-8', 'store_id': 'Oro Valley_Arizona_85737', 'reason_code': 'LATE', 'return_amount': Decimal('17.94'), 'quantity_returned': 3, 'return_condition': 'Damaged', 'original_sale_id': 'SALE38464', 'original_sale_date': datetime.date(2025, 4, 28), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688428)}, {'return_id': 'RET000005', 'return_date': datetime.date(2025, 5, 25), 'product_id': 'a2f02b89-823f-44c6-9', 'store_id': 'Lorain_Ohio_44052', 'reason_code': 'PERF', 'return_amount': Decimal('19.42'), 'quantity_returned': 2, 'return_condition': 'Like New', 'original_sale_id': 'SALE82501', 'original_sale_date': datetime.date(2025, 5, 21), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688435)}, {'return_id': 'RET000006', 'return_date': datetime.date(2025, 4, 28), 'product_id': '376a9935-783f-428b-8', 'store_id': 'Collierville_Tennessee_38017', 'reason_code': 'PERF', 'return_amount': Decimal('79.96'), 'quantity_returned': 2, 'return_condition': 'New', 'original_sale_id': 'SALE24305', 'original_sale_date': datetime.date(2025, 4, 17), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688441)}, {'return_id': 'RET000007', 'return_date': datetime.date(2025, 5, 1), 'product_id': '621306c7-2eb8-4951-9', 'store_id': 'Durango_Colorado_81301', 'reason_code': 'LATE', 'return_amount': Decimal('87.14'), 'quantity_returned': 2, 'return_condition': 'Defective', 'original_sale_id': 'SALE29979', 'original_sale_date': datetime.date(2025, 4, 10), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688447)}, {'return_id': 'RET000008', 'return_date': datetime.date(2025, 4, 30), 'product_id': '420a1e94-4967-4387-8', 'store_id': 'Galesburg_Illinois_61401', 'reason_code': 'CHANGE', 'return_amount': Decimal('5.78'), 'quantity_returned': 1, 'return_condition': 'Used', 'original_sale_id': 'SALE60337', 'original_sale_date': datetime.date(2025, 3, 31), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 688470)}  ... displaying 10 of 200 total bound parameter sets ...  {'return_id': 'RET000199', 'return_date': datetime.date(2025, 5, 16), 'product_id': '5564d9af-7a2e-4f8b-9', 'store_id': 'Germantown_Tennessee_38138', 'reason_code': 'CHANGE', 'return_amount': Decimal('19.90'), 'quantity_returned': 1, 'return_condition': 'Like New', 'original_sale_id': 'SALE83255', 'original_sale_date': datetime.date(2025, 4, 26), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 689611)}, {'return_id': 'RET000200', 'return_date': datetime.date(2025, 5, 1), 'product_id': '488a83b1-98f1-4345-a', 'store_id': 'Hastings_Nebraska_68901', 'reason_code': 'WRONG', 'return_amount': Decimal('39.20'), 'quantity_returned': 5, 'return_condition': 'Like New', 'original_sale_id': 'SALE72615', 'original_sale_date': datetime.date(2025, 4, 3), 'source_system': 'Synthetic Data', 'load_timestamp': datetime.datetime(2025, 5, 27, 19, 55, 5, 689616)})]
(Background on this error at: https://sqlalche.me/e/14/f405); 126)
[2025-05-27T19:55:05.743+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-27T19:55:05.756+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
