[2025-05-27T18:28:17.267+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.load_to_ods manual__2025-05-27T18:28:15+00:00 [queued]>
[2025-05-27T18:28:17.275+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.load_to_ods manual__2025-05-27T18:28:15+00:00 [queued]>
[2025-05-27T18:28:17.276+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-27T18:28:17.285+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_ods> on 2025-05-27 18:28:15+00:00
[2025-05-27T18:28:17.290+0000] {standard_task_runner.py:57} INFO - Started process 208 to run task
[2025-05-27T18:28:17.296+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'load_to_ods', 'manual__2025-05-27T18:28:15+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmpvousr4yg']
[2025-05-27T18:28:17.302+0000] {standard_task_runner.py:85} INFO - Job 230: Subtask load_to_ods
[2025-05-27T18:28:17.333+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.load_to_ods manual__2025-05-27T18:28:15+00:00 [running]> on host d80f98a6628f
[2025-05-27T18:28:17.594+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='load_to_ods' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T18:28:15+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T18:28:15+00:00'
[2025-05-27T18:28:17.628+0000] {logging_mixin.py:154} INFO - Loaded 8399 rows from CSV file.
[2025-05-27T18:28:17.916+0000] {logging_mixin.py:154} INFO - Loaded 1459 records into ods_date.
[2025-05-27T18:28:18.406+0000] {logging_mixin.py:154} INFO - Loaded 3011 records into ods_customer.
[2025-05-27T18:28:18.610+0000] {logging_mixin.py:154} INFO - Loaded 1314 records into ods_product.
[2025-05-27T18:28:18.678+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 1000, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.UndefinedColumn: column "effective_date" of relation "ods_store" does not exist
LINE 4:                     region, store_size_sqft, effective_date,...
                                                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/walmart_etl_dag.py", line 84, in etl_load_to_ods
    load_ods_layer(engine, df)
  File "/opt/airflow/walmart-etl/etl_data_loader.py", line 339, in load_ods_layer
    load_ods_store_dimension(engine, df)
  File "/opt/airflow/walmart-etl/etl_data_loader.py", line 228, in load_ods_store_dimension
    conn.execute(text("""
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 1000, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "effective_date" of relation "ods_store" does not exist
LINE 4:                     region, store_size_sqft, effective_date,...
                                                     ^

[SQL: 
                INSERT INTO ods_store (
                    store_id, store_name, location, city, state, zip_code,
                    region, store_size_sqft, effective_date, source_system, load_timestamp
                ) VALUES (
                    %(store_id)s, %(store_name)s, %(location)s, %(city)s, %(state)s, %(zip_code)s,
                    %(region)s, %(store_size_sqft)s, %(effective_date)s, %(source_system)s, %(load_timestamp)s
                )
                ON CONFLICT (store_id) DO NOTHING
            ]
[parameters: ({'store_id': 'McKeesport_Pennsylvania_15131', 'store_name': 'McKeesport Store', 'location': 'McKeesport, Pennsylvania 15131', 'city': 'McKeesport', 'state': 'Pennsylvania', 'zip_code': 15131, 'region': 'East', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613645)}, {'store_id': 'Bowie_Maryland_20715', 'store_name': 'Bowie Store', 'location': 'Bowie, Maryland 20715', 'city': 'Bowie', 'state': 'Maryland', 'zip_code': 20715, 'region': 'East', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613703)}, {'store_id': 'Napa_California_94559', 'store_name': 'Napa Store', 'location': 'Napa, California 94559', 'city': 'Napa', 'state': 'California', 'zip_code': 94559, 'region': 'West', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613736)}, {'store_id': 'Montebello_California_90640', 'store_name': 'Montebello Store', 'location': 'Montebello, California 90640', 'city': 'Montebello', 'state': 'California', 'zip_code': 90640, 'region': 'West', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613767)}, {'store_id': 'Prior Lake_Minnesota_55372', 'store_name': 'Prior Lake Store', 'location': 'Prior Lake, Minnesota 55372', 'city': 'Prior Lake', 'state': 'Minnesota', 'zip_code': 55372, 'region': 'Central', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613798)}, {'store_id': 'Phenix City_Alabama_36869', 'store_name': 'Phenix City Store', 'location': 'Phenix City, Alabama 36869', 'city': 'Phenix City', 'state': 'Alabama', 'zip_code': 36869, 'region': 'South', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613829)}, {'store_id': 'Draper_Utah_84020', 'store_name': 'Draper Store', 'location': 'Draper, Utah 84020', 'city': 'Draper', 'state': 'Utah', 'zip_code': 84020, 'region': 'West', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613859)}, {'store_id': 'Lake Oswego_Oregon_97035', 'store_name': 'Lake Oswego Store', 'location': 'Lake Oswego, Oregon 97035', 'city': 'Lake Oswego', 'state': 'Oregon', 'zip_code': 97035, 'region': 'West', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613888)}  ... displaying 10 of 1636 total bound parameter sets ...  {'store_id': 'Marblehead_MA_1945', 'store_name': 'Marblehead Store', 'location': 'Marblehead, MA 1945', 'city': 'Marblehead', 'state': 'MA', 'zip_code': 1945, 'region': 'East', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 670979)}, {'store_id': 'Needham_MA_2492', 'store_name': 'Needham Store', 'location': 'Needham, MA 2492', 'city': 'Needham', 'state': 'MA', 'zip_code': 2492, 'region': 'East', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 671007)})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-05-27T18:28:18.688+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=walmart_etl_dag, task_id=load_to_ods, execution_date=20250527T182815, start_date=20250527T182817, end_date=20250527T182818
[2025-05-27T18:28:18.697+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 230 for task load_to_ods ((psycopg2.errors.UndefinedColumn) column "effective_date" of relation "ods_store" does not exist
LINE 4:                     region, store_size_sqft, effective_date,...
                                                     ^

[SQL: 
                INSERT INTO ods_store (
                    store_id, store_name, location, city, state, zip_code,
                    region, store_size_sqft, effective_date, source_system, load_timestamp
                ) VALUES (
                    %(store_id)s, %(store_name)s, %(location)s, %(city)s, %(state)s, %(zip_code)s,
                    %(region)s, %(store_size_sqft)s, %(effective_date)s, %(source_system)s, %(load_timestamp)s
                )
                ON CONFLICT (store_id) DO NOTHING
            ]
[parameters: ({'store_id': 'McKeesport_Pennsylvania_15131', 'store_name': 'McKeesport Store', 'location': 'McKeesport, Pennsylvania 15131', 'city': 'McKeesport', 'state': 'Pennsylvania', 'zip_code': 15131, 'region': 'East', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613645)}, {'store_id': 'Bowie_Maryland_20715', 'store_name': 'Bowie Store', 'location': 'Bowie, Maryland 20715', 'city': 'Bowie', 'state': 'Maryland', 'zip_code': 20715, 'region': 'East', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613703)}, {'store_id': 'Napa_California_94559', 'store_name': 'Napa Store', 'location': 'Napa, California 94559', 'city': 'Napa', 'state': 'California', 'zip_code': 94559, 'region': 'West', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613736)}, {'store_id': 'Montebello_California_90640', 'store_name': 'Montebello Store', 'location': 'Montebello, California 90640', 'city': 'Montebello', 'state': 'California', 'zip_code': 90640, 'region': 'West', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613767)}, {'store_id': 'Prior Lake_Minnesota_55372', 'store_name': 'Prior Lake Store', 'location': 'Prior Lake, Minnesota 55372', 'city': 'Prior Lake', 'state': 'Minnesota', 'zip_code': 55372, 'region': 'Central', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613798)}, {'store_id': 'Phenix City_Alabama_36869', 'store_name': 'Phenix City Store', 'location': 'Phenix City, Alabama 36869', 'city': 'Phenix City', 'state': 'Alabama', 'zip_code': 36869, 'region': 'South', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613829)}, {'store_id': 'Draper_Utah_84020', 'store_name': 'Draper Store', 'location': 'Draper, Utah 84020', 'city': 'Draper', 'state': 'Utah', 'zip_code': 84020, 'region': 'West', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613859)}, {'store_id': 'Lake Oswego_Oregon_97035', 'store_name': 'Lake Oswego Store', 'location': 'Lake Oswego, Oregon 97035', 'city': 'Lake Oswego', 'state': 'Oregon', 'zip_code': 97035, 'region': 'West', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 613888)}  ... displaying 10 of 1636 total bound parameter sets ...  {'store_id': 'Marblehead_MA_1945', 'store_name': 'Marblehead Store', 'location': 'Marblehead, MA 1945', 'city': 'Marblehead', 'state': 'MA', 'zip_code': 1945, 'region': 'East', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 670979)}, {'store_id': 'Needham_MA_2492', 'store_name': 'Needham Store', 'location': 'Needham, MA 2492', 'city': 'Needham', 'state': 'MA', 'zip_code': 2492, 'region': 'East', 'store_size_sqft': None, 'effective_date': datetime.date(2025, 5, 27), 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 18, 28, 18, 671007)})]
(Background on this error at: https://sqlalche.me/e/14/f405); 208)
[2025-05-27T18:28:18.719+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-27T18:28:18.770+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
