[2025-05-27T19:28:26.772+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T19:28:14+00:00 [queued]>
[2025-05-27T19:28:26.776+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T19:28:14+00:00 [queued]>
[2025-05-27T19:28:26.777+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-27T19:28:26.783+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_quality_checks> on 2025-05-27 19:28:14+00:00
[2025-05-27T19:28:26.787+0000] {standard_task_runner.py:57} INFO - Started process 1368 to run task
[2025-05-27T19:28:26.790+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'data_quality_checks', 'manual__2025-05-27T19:28:14+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmp151x6mtw']
[2025-05-27T19:28:26.793+0000] {standard_task_runner.py:85} INFO - Job 313: Subtask data_quality_checks
[2025-05-27T19:28:26.828+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T19:28:14+00:00 [running]> on host d80f98a6628f
[2025-05-27T19:28:27.118+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T19:28:14+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T19:28:14+00:00'
[2025-05-27T19:28:27.127+0000] {logging_mixin.py:154} INFO - Found 1314 records in tgt_dim_product
[2025-05-27T19:28:27.129+0000] {logging_mixin.py:154} INFO - Found 1636 records in tgt_dim_store
[2025-05-27T19:28:27.134+0000] {logging_mixin.py:154} INFO - Found 8399 records in tgt_fact_sales
[2025-05-27T19:28:27.135+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_inventory
[2025-05-27T19:28:27.135+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_returns
[2025-05-27T19:28:27.136+0000] {python.py:194} INFO - Done. Returned value was: Data quality checks completed. Products: 1314, Stores: 1636, Sales: 8399, Inventory: 0, Returns: 0
[2025-05-27T19:28:27.154+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=walmart_etl_dag, task_id=data_quality_checks, execution_date=20250527T192814, start_date=20250527T192826, end_date=20250527T192827
[2025-05-27T19:28:27.183+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-27T19:28:27.196+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
