[2025-05-27T21:02:46.801+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.load_to_ods manual__2025-05-27T21:02:44.804749+00:00 [queued]>
[2025-05-27T21:02:46.814+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.load_to_ods manual__2025-05-27T21:02:44.804749+00:00 [queued]>
[2025-05-27T21:02:46.815+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-27T21:02:46.825+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_ods> on 2025-05-27 21:02:44.804749+00:00
[2025-05-27T21:02:46.832+0000] {standard_task_runner.py:57} INFO - Started process 86 to run task
[2025-05-27T21:02:46.835+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'load_to_ods', 'manual__2025-05-27T21:02:44.804749+00:00', '--job-id', '381', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmp5kmgdlrv']
[2025-05-27T21:02:46.837+0000] {standard_task_runner.py:85} INFO - Job 381: Subtask load_to_ods
[2025-05-27T21:02:47.112+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.load_to_ods manual__2025-05-27T21:02:44.804749+00:00 [running]> on host 16a8877c41cf
[2025-05-27T21:02:47.171+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='load_to_ods' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T21:02:44.804749+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T21:02:44.804749+00:00'
[2025-05-27T21:02:47.176+0000] {logging_mixin.py:154} INFO - Found 500 inventory records and 200 returns records in ODS
[2025-05-27T21:02:47.186+0000] {logging_mixin.py:154} INFO - Loaded 5 rows from CSV file.
[2025-05-27T21:02:47.196+0000] {logging_mixin.py:154} INFO - Loaded 1 records into ods_date.
[2025-05-27T21:02:47.202+0000] {logging_mixin.py:154} INFO - Loaded 5 records into ods_customer.
[2025-05-27T21:02:47.205+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 1000, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(50)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/walmart_etl_dag.py", line 87, in etl_load_to_ods
    load_ods_layer(engine, df)
  File "/opt/airflow/walmart-etl/etl_data_loader.py", line 433, in load_ods_layer
    load_ods_product_dimension(engine, df)
  File "/opt/airflow/walmart-etl/etl_data_loader.py", line 234, in load_ods_product_dimension
    conn.execute(text("""
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 1000, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(50)

[SQL: 
                INSERT INTO ods_product (
                    product_id, product_name, product_category, product_sub_category,
                    product_container, product_base_margin, unit_price, supplier_id,
                    source_system, load_timestamp
                ) VALUES (
                    %(product_id)s, %(product_name)s, %(product_category)s, %(product_sub_category)s,
                    %(product_container)s, %(product_base_margin)s, %(unit_price)s, %(supplier_id)s,
                    %(source_system)s, %(load_timestamp)s
                )
                ON CONFLICT (product_id) DO NOTHING
            ]
[parameters: ({'product_id': '060a94b7efdfe2992d67', 'product_name': ' Sand"', 'product_category': 'Small Box', 'product_sub_category': 'Storage & Organization', 'product_container': 'Tennsco Stur-D-Stor Boltless Shelving, 5 Shelves, 24 Deep', 'product_base_margin': nan, 'unit_price': 199.99, 'supplier_id': None, 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 21, 2, 47, 203734)}, {'product_id': 'ba0bbc1ae1eb5438089d', 'product_name': 'Office Furnishings', 'product_category': 'Large Box', 'product_sub_category': '-342.91', 'product_container': 'Artistic Insta-Plaque', 'product_base_margin': nan, 'unit_price': 20715.0, 'supplier_id': None, 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 21, 2, 47, 203781)}, {'product_id': '6c6786f99605b5180577', 'product_name': 'Pens & Art Supplies', 'product_category': 'Jumbo Drum', 'product_sub_category': '-193.08', 'product_container': 'Crayola Colored Pencils', 'product_base_margin': nan, 'unit_price': 94559.0, 'supplier_id': None, 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 21, 2, 47, 203815)}, {'product_id': '25a4fa96dae848c643ea', 'product_name': ' 400 Sets per Book', 'product_category': 'Wrap Bag', 'product_sub_category': 'Paper', 'product_container': 'Wirebound Four 2-3/4 x 5 Forms per Page', 'product_base_margin': nan, 'unit_price': 8.99, 'supplier_id': None, 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 21, 2, 47, 203853)}, {'product_id': '3a9f4cb07f0e49b5d043', 'product_name': 'Telephones and Communication', 'product_category': 'Jumbo Drum', 'product_sub_category': '-1049.85', 'product_container': 'i470', 'product_base_margin': nan, 'unit_price': 94559.0, 'supplier_id': None, 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 21, 2, 47, 203885)})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
[2025-05-27T21:02:47.214+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=walmart_etl_dag, task_id=load_to_ods, execution_date=20250527T210244, start_date=20250527T210246, end_date=20250527T210247
[2025-05-27T21:02:47.221+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 381 for task load_to_ods ((psycopg2.errors.StringDataRightTruncation) value too long for type character varying(50)

[SQL: 
                INSERT INTO ods_product (
                    product_id, product_name, product_category, product_sub_category,
                    product_container, product_base_margin, unit_price, supplier_id,
                    source_system, load_timestamp
                ) VALUES (
                    %(product_id)s, %(product_name)s, %(product_category)s, %(product_sub_category)s,
                    %(product_container)s, %(product_base_margin)s, %(unit_price)s, %(supplier_id)s,
                    %(source_system)s, %(load_timestamp)s
                )
                ON CONFLICT (product_id) DO NOTHING
            ]
[parameters: ({'product_id': '060a94b7efdfe2992d67', 'product_name': ' Sand"', 'product_category': 'Small Box', 'product_sub_category': 'Storage & Organization', 'product_container': 'Tennsco Stur-D-Stor Boltless Shelving, 5 Shelves, 24 Deep', 'product_base_margin': nan, 'unit_price': 199.99, 'supplier_id': None, 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 21, 2, 47, 203734)}, {'product_id': 'ba0bbc1ae1eb5438089d', 'product_name': 'Office Furnishings', 'product_category': 'Large Box', 'product_sub_category': '-342.91', 'product_container': 'Artistic Insta-Plaque', 'product_base_margin': nan, 'unit_price': 20715.0, 'supplier_id': None, 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 21, 2, 47, 203781)}, {'product_id': '6c6786f99605b5180577', 'product_name': 'Pens & Art Supplies', 'product_category': 'Jumbo Drum', 'product_sub_category': '-193.08', 'product_container': 'Crayola Colored Pencils', 'product_base_margin': nan, 'unit_price': 94559.0, 'supplier_id': None, 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 21, 2, 47, 203815)}, {'product_id': '25a4fa96dae848c643ea', 'product_name': ' 400 Sets per Book', 'product_category': 'Wrap Bag', 'product_sub_category': 'Paper', 'product_container': 'Wirebound Four 2-3/4 x 5 Forms per Page', 'product_base_margin': nan, 'unit_price': 8.99, 'supplier_id': None, 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 21, 2, 47, 203853)}, {'product_id': '3a9f4cb07f0e49b5d043', 'product_name': 'Telephones and Communication', 'product_category': 'Jumbo Drum', 'product_sub_category': '-1049.85', 'product_container': 'i470', 'product_base_margin': nan, 'unit_price': 94559.0, 'supplier_id': None, 'source_system': 'CSV Import', 'load_timestamp': datetime.datetime(2025, 5, 27, 21, 2, 47, 203885)})]
(Background on this error at: https://sqlalche.me/e/14/9h9h); 86)
[2025-05-27T21:02:47.274+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-27T21:02:47.418+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
