[2025-05-28T05:31:49.722+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-28T05:31:39+00:00 [queued]>
[2025-05-28T05:31:49.726+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-28T05:31:39+00:00 [queued]>
[2025-05-28T05:31:49.726+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-28T05:31:49.732+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_quality_checks> on 2025-05-28 05:31:39+00:00
[2025-05-28T05:31:49.734+0000] {standard_task_runner.py:57} INFO - Started process 464 to run task
[2025-05-28T05:31:49.737+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'data_quality_checks', 'manual__2025-05-28T05:31:39+00:00', '--job-id', '593', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmp1yhfwya1']
[2025-05-28T05:31:49.739+0000] {standard_task_runner.py:85} INFO - Job 593: Subtask data_quality_checks
[2025-05-28T05:31:49.766+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-28T05:31:39+00:00 [running]> on host 54aadfabdafd
[2025-05-28T05:31:49.897+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T05:31:39+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T05:31:39+00:00'
[2025-05-28T05:31:49.901+0000] {logging_mixin.py:154} INFO - Found 1263 records in tgt_dim_product
[2025-05-28T05:31:49.902+0000] {logging_mixin.py:154} INFO - Found 1421 records in tgt_dim_store
[2025-05-28T05:31:49.902+0000] {logging_mixin.py:154} INFO - Found 8399 records in tgt_fact_sales
[2025-05-28T05:31:49.903+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_inventory
[2025-05-28T05:31:49.903+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_returns
[2025-05-28T05:31:49.904+0000] {logging_mixin.py:154} INFO - Found 0 historical product records
[2025-05-28T05:31:49.904+0000] {logging_mixin.py:154} INFO - Found 0 historical store records
[2025-05-28T05:31:49.904+0000] {python.py:194} INFO - Done. Returned value was: Data quality checks completed: {'tgt_dim_product': 1263, 'tgt_dim_store': 1421, 'tgt_fact_sales': 8399, 'tgt_fact_inventory': 0, 'tgt_fact_returns': 0}
[2025-05-28T05:31:49.914+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=walmart_etl_dag, task_id=data_quality_checks, execution_date=20250528T053139, start_date=20250528T053149, end_date=20250528T053149
[2025-05-28T05:31:49.923+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-28T05:31:49.931+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
