[2025-05-27T22:17:44.955+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T22:17:34.551152+00:00 [queued]>
[2025-05-27T22:17:44.959+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T22:17:34.551152+00:00 [queued]>
[2025-05-27T22:17:44.960+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-27T22:17:44.965+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_quality_checks> on 2025-05-27 22:17:34.551152+00:00
[2025-05-27T22:17:44.969+0000] {standard_task_runner.py:57} INFO - Started process 154 to run task
[2025-05-27T22:17:44.971+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'data_quality_checks', 'manual__2025-05-27T22:17:34.551152+00:00', '--job-id', '455', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmp1u9dze2u']
[2025-05-27T22:17:44.973+0000] {standard_task_runner.py:85} INFO - Job 455: Subtask data_quality_checks
[2025-05-27T22:17:44.996+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T22:17:34.551152+00:00 [running]> on host e3db230d44e2
[2025-05-27T22:17:45.160+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T22:17:34.551152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T22:17:34.551152+00:00'
[2025-05-27T22:17:45.165+0000] {logging_mixin.py:154} INFO - Found 1263 records in tgt_dim_product
[2025-05-27T22:17:45.166+0000] {logging_mixin.py:154} INFO - Found 1421 records in tgt_dim_store
[2025-05-27T22:17:45.174+0000] {logging_mixin.py:154} INFO - Found 8399 records in tgt_fact_sales
[2025-05-27T22:17:45.175+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_inventory
[2025-05-27T22:17:45.175+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_returns
[2025-05-27T22:17:45.176+0000] {logging_mixin.py:154} INFO - Found 0 historical product records
[2025-05-27T22:17:45.176+0000] {logging_mixin.py:154} INFO - Found 0 historical store records
[2025-05-27T22:17:45.176+0000] {python.py:194} INFO - Done. Returned value was: Data quality checks completed: {'tgt_dim_product': 1263, 'tgt_dim_store': 1421, 'tgt_fact_sales': 8399, 'tgt_fact_inventory': 0, 'tgt_fact_returns': 0}
[2025-05-27T22:17:45.195+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=walmart_etl_dag, task_id=data_quality_checks, execution_date=20250527T221734, start_date=20250527T221744, end_date=20250527T221745
[2025-05-27T22:17:45.240+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-27T22:17:45.253+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
