[2025-05-27T21:52:03.401+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T21:51:54.585218+00:00 [queued]>
[2025-05-27T21:52:03.407+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T21:51:54.585218+00:00 [queued]>
[2025-05-27T21:52:03.407+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-27T21:52:03.415+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_quality_checks> on 2025-05-27 21:51:54.585218+00:00
[2025-05-27T21:52:03.430+0000] {standard_task_runner.py:57} INFO - Started process 121 to run task
[2025-05-27T21:52:03.433+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'walmart_etl_dag', 'data_quality_checks', 'manual__2025-05-27T21:51:54.585218+00:00', '--job-id', '414', '--raw', '--subdir', 'DAGS_FOLDER/walmart_etl_dag.py', '--cfg-path', '/tmp/tmphaqefxa1']
[2025-05-27T21:52:03.435+0000] {standard_task_runner.py:85} INFO - Job 414: Subtask data_quality_checks
[2025-05-27T21:52:03.466+0000] {task_command.py:416} INFO - Running <TaskInstance: walmart_etl_dag.data_quality_checks manual__2025-05-27T21:51:54.585218+00:00 [running]> on host 869a336fecbe
[2025-05-27T21:52:03.737+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='walmart_etl_dag' AIRFLOW_CTX_TASK_ID='data_quality_checks' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T21:51:54.585218+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-27T21:51:54.585218+00:00'
[2025-05-27T21:52:03.744+0000] {logging_mixin.py:154} INFO - Found 3 records in tgt_dim_product
[2025-05-27T21:52:03.745+0000] {logging_mixin.py:154} INFO - Found 3 records in tgt_dim_store
[2025-05-27T21:52:03.746+0000] {logging_mixin.py:154} INFO - Found 3 records in tgt_fact_sales
[2025-05-27T21:52:03.746+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_inventory
[2025-05-27T21:52:03.747+0000] {logging_mixin.py:154} INFO - WARNING: No data in tgt_fact_returns
[2025-05-27T21:52:03.748+0000] {logging_mixin.py:154} INFO - Found 0 historical product records
[2025-05-27T21:52:03.748+0000] {logging_mixin.py:154} INFO - Found 0 historical store records
[2025-05-27T21:52:03.748+0000] {python.py:194} INFO - Done. Returned value was: Data quality checks completed: {'tgt_dim_product': 3, 'tgt_dim_store': 3, 'tgt_fact_sales': 3, 'tgt_fact_inventory': 0, 'tgt_fact_returns': 0}
[2025-05-27T21:52:03.763+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=walmart_etl_dag, task_id=data_quality_checks, execution_date=20250527T215154, start_date=20250527T215203, end_date=20250527T215203
[2025-05-27T21:52:03.781+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-27T21:52:03.796+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
